---
navigation:
  default:
    search: false
    tabs:
      - name: 
        link: /
        icon: home
        position: left

      - name: Docs
        link: /docs
        icon: manual
        position: left

      - name: Settings
        link: /settings
        icon: cog
        position: right
