---
filter:
  - active
  - responsive
  - hover
  - group-hover
backdropFilter:
  - active
  - responsive
  - hover
  - group-hover
accessibility:
  - active
  - responsive
  - focus-within
  - focus
alignContent:
  - active
  - responsive
alignItems:
  - active
  - responsive
alignSelf:
  - active
  - responsive
animation:
  - active
  - responsive
appearance:
  - active
  - responsive
backgroundAttachment:
  - active
  - responsive
backgroundClip:
  - active
  - responsive
backgroundColor:
  - active
  - responsive
  - dark
  - group-hover
  - focus-within
  - hover
  - focus
backgroundImage:
  - active
  - responsive
backgroundOpacity:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
backgroundPosition:
  - active
  - responsive
backgroundRepeat:
  - active
  - responsive
backgroundSize:
  - active
  - responsive
borderCollapse:
  - active
  - responsive
borderColor:
  - active
  - responsive
  - dark
  - group-hover
  - focus-within
  - hover
  - focus
borderOpacity:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
borderRadius:
  - active
  - responsive
borderStyle:
  - active
  - responsive
borderWidth:
  - active
  - responsive
boxShadow:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
boxSizing:
  - active
  - hover
  - group-hover
  - responsive
clear:
  - active
  - hover
  - group-hover
  - responsive
container:
  - active
  - hover
  - group-hover
  - responsive
cursor:
  - active
  - hover
  - group-hover
  - responsive
display:
  - active
  - hover
  - group-hover
  - responsive
divideColor:
  - active
  - hover
  - group-hover
  - responsive
  - dark
divideOpacity:
  - active
  - hover
  - group-hover
  - responsive
divideStyle:
  - active
  - hover
  - group-hover
  - responsive
divideWidth:
  - active
  - hover
  - group-hover
  - responsive
fill:
  - active
  - hover
  - group-hover
  - responsive
flex:
  - active
  - hover
  - group-hover
  - responsive
flexDirection:
  - active
  - hover
  - group-hover
  - responsive
flexGrow:
  - active
  - hover
  - group-hover
  - responsive
flexShrink:
  - active
  - hover
  - group-hover
  - responsive
flexWrap:
  - active
  - hover
  - group-hover
  - responsive
float:
  - active
  - hover
  - group-hover
  - responsive
fontFamily:
  - active
  - hover
  - group-hover
  - responsive
fontSize:
  - active
  - hover
  - group-hover
  - responsive
fontSmoothing:
  - active
  - hover
  - group-hover
  - responsive
fontStyle:
  - active
  - hover
  - group-hover
  - responsive
fontVariantNumeric:
  - active
  - hover
  - group-hover
  - responsive
fontWeight:
  - active
  - hover
  - group-hover
  - responsive
gap:
  - active
  - hover
  - group-hover
  - responsive
gradientColorStops:
  - active
  - responsive
  - dark
  - hover
  - focus
gridAutoColumns:
  - active
  - hover
  - group-hover
  - responsive
gridAutoFlow:
  - active
  - hover
  - group-hover
  - responsive
gridAutoRows:
  - active
  - hover
  - group-hover
  - responsive
gridColumn:
  - active
  - hover
  - group-hover
  - responsive
gridColumnEnd:
  - active
  - hover
  - group-hover
  - responsive
gridColumnStart:
  - active
  - hover
  - group-hover
  - responsive
gridRow:
  - active
  - hover
  - group-hover
  - responsive
gridRowEnd:
  - active
  - hover
  - group-hover
  - responsive
gridRowStart:
  - active
  - responsive
gridTemplateColumns:
  - active
  - hover
  - group-hover
  - responsive
gridTemplateRows:
  - active
  - hover
  - group-hover
  - responsive
height:
  - active
  - hover
  - group-hover
  - responsive
inset:
  - active
  - hover
  - group-hover
  - responsive
  - hover
  - focus
justifyContent:
  - active
  - hover
  - group-hover
  - responsive
justifyItems:
  - active
  - hover
  - group-hover
  - responsive
justifySelf:
  - active
  - hover
  - group-hover
  - responsive
letterSpacing:
  - active
  - hover
  - group-hover
  - responsive
lineHeight:
  - active
  - hover
  - group-hover
  - responsive
listStylePosition:
  - active
  - hover
  - group-hover
  - responsive
listStyleType:
  - active
  - hover
  - group-hover
  - responsive
margin:
  - active
  - hover
  - group-hover
  - responsive
maxHeight:
  - active
  - responsive
maxWidth:
  - active
  - hover
  - group-hover
  - responsive
minHeight:
  - active
  - hover
  - group-hover
  - responsive
minWidth:
  - active
  - hover
  - group-hover
  - responsive
objectFit:
  - active
  - hover
  - group-hover
  - responsive
objectPosition:
  - active
  - hover
  - group-hover
  - responsive
opacity:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
order:
  - active
  - hover
  - group-hover
  - responsive
outline:
  - active
  - hover
  - group-hover
  - responsive
  - focus-within
  - focus
overflow:
  - active
  - hover
  - group-hover
  - responsive
overscrollBehavior:
  - active
  - hover
  - group-hover
  - responsive
padding:
  - active
  - hover
  - group-hover
  - responsive
placeContent:
  - active
  - hover
  - group-hover
  - responsive
placeItems:
  - active
  - hover
  - group-hover
  - responsive
placeSelf:
  - active
  - hover
  - group-hover
  - responsive
placeholderColor:
  - active
  - hover
  - group-hover
  - responsive
  - dark
  - focus
placeholderOpacity:
  - active
  - hover
  - group-hover
  - responsive
  - focus
pointerEvents:
  - active
  - hover
  - group-hover
  - responsive
position:
  - active
  - hover
  - group-hover
  - responsive
resize:
  - active
  - hover
  - group-hover
  - responsive
ringColor:
  - active
  - responsive
  - dark
  - focus-within
  - focus
  - hover
  - group-hover
ringOffsetColor:
  - active
  - responsive
  - dark
  - focus-within
  - focus
  - hover
  - group-hover
ringOffsetWidth:
  - active
  - hover
  - group-hover
  - responsive
  - focus-within
  - focus
  - hover
ringOpacity:
  - active
  - hover
  - group-hover
  - responsive
  - focus-within
  - focus
  - hover
ringWidth:
  - active
  - hover
  - group-hover
  - responsive
  - focus-within
  - focus
  - hover
rotate:
  - active
  - hover
  - group-hover
  - responsive
  - hover
  - focus
scale:
  - active
  - hover
  - group-hover
  - responsive
  - hover
  - focus
skew:
  - active
  - hover
  - group-hover
  - responsive
  - hover
  - focus
space:
  - active
  - hover
  - group-hover
  - responsive
stroke:
  - active
  - hover
  - group-hover
  - responsive
strokeWidth:
  - active
  - hover
  - group-hover
  - responsive
tableLayout:
  - active
  - hover
  - group-hover
  - responsive
textAlign:
  - active
  - hover
  - group-hover
  - responsive
textColor:
  - active
  - responsive
  - dark
  - group-hover
  - focus-within
  - hover
  - focus
textDecoration:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
textOpacity:
  - active
  - responsive
  - group-hover
  - focus-within
  - hover
  - focus
textOverflow:
  - active
  - hover
  - group-hover
  - responsive
textTransform:
  - active
  - hover
  - group-hover
  - responsive
transform:
  - active
  - hover
  - group-hover
  - responsive
transformOrigin:
  - active
  - hover
  - group-hover
  - responsive
transitionDelay:
  - active
  - hover
  - group-hover
  - responsive
transitionDuration:
  - active
  - hover
  - group-hover
  - responsive
transitionProperty:
  - active
  - hover
  - group-hover
  - responsive
transitionTimingFunction:
  - active
  - hover
  - group-hover
  - responsive
translate:
  - active
  - hover
  - group-hover
  - responsive
  - hover
  - focus
userSelect:
  - active
  - hover
  - group-hover
  - responsive
verticalAlign:
  - active
  - hover
  - group-hover
  - responsive
visibility:
  - active
  - hover
  - group-hover
  - responsive
whitespace:
  - active
  - hover
  - group-hover
  - responsive
width:
  - active
  - hover
  - group-hover
  - responsive
wordBreak:
  - active
  - hover
  - group-hover
  - responsive
zIndex:
  - active
  - hover
  - group-hover
  - responsive
  - focus-within
  - focus
